project:
  type: book
  output-dir: docs
  resources:
    - images/
book:
  title: ""
  chapters:
    - index.qmd
    - WhatsNew.qmd
    - SiteHistory.qmd
    - ClimateChange.qmd
    - Hydrology.qmd

  sidebar:
    style: docked
    collapse-level: 2
  search: false  

format:
  html:
    title-block: false
    css: styles.css
    toc: true
    toc-title: "Chapter Sections"
    include-before-body: includes/banner.html
    
from: markdown+raw_html